apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: events
spec:
  delivery:
    deadLetterSink:
      ref:
          apiVersion: serving.knative.dev/v1
          kind: Service
          name: sockeye
    backoffDelay: "PT0.5S"     # or ISO8601 duration
    backoffPolicy: exponential # or linear
    retry: 2
---
apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: ping-sockeye
spec:
  data: '{"name": "triggermesh"}'
  schedule: "*/1 * * * *"
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: events
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sockeye
spec:
  template:
    spec:
      containers:
        - image: docker.io/n3wscott/sockeye:v0.7.0@sha256:e603d8494eeacce966e57f8f508e4c4f6bebc71d095e3f5a0a1abaf42c5f0e48
---

apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: failtest
spec:
  broker: events
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display


---

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: event-display
spec:
  template:
    spec:
      containers:
      - image: docker.io/n3wscott/sockeye:v0.7.0@sha256:e603d8494eeacce966e57f8f508e4c4f6bebc71d095e3f5a0a1abaf42c5f0e48
        name: user-container
