copyright: 2021, TriggerMesh
site_author: TriggerMesh
site_description: TriggerMesh's Docs
site_name: TriggerMesh
site_url: https://docs.triggermesh.io
repo_url: https://github.com/triggermesh/docs
google_analytics: ['UA-127409524-1', 'docs.triggermesh.io']
extra_css: [extra.css]
extra_javascript: [extra.js]
nav:
    - Home: index.md
    - Guides:
      - 'Getting Started': guides/gettingstarted.md
      - 'CD': guides/cd.md
      - 'Actions': guides/actions.md
      - 'Bridge': guides/bridge.md
      - 'Secrets': guides/secrets.md
    - Client:
      - 'Installation': 'tm/install.md'
      - 'Configuration': 'tm/configuration.md'
      - 'Usage': 'tm/usage.md'
      - 'Registry': 'tm/registry.md'
      - 'Serverless Manifest': 'tm/serverless.md'
    - Sources: sources/index.md
    - Targets: targets/index.md
    - API: apis/index.md
    - Cloud: https://cloud.triggermesh.io
    - About: about.md
theme:
  name: material
  favicon: images/favicon.ico
  logo: images/tmLogo-white.png

markdown_extensions:
  - attr_list
  - admonition
